package com.team27.lucky3.backend.entity.enums;

public enum RideStatus {
    PENDING, ACCEPTED, SCHEDULED, ACTIVE, IN_PROGRESS, FINISHED, REJECTED, PANIC, CANCELLED, CANCELLED_BY_DRIVER, CANCELLED_BY_PASSENGER
}
